# Reference: https://github.com/codingjerk/dotfiles/tree/main
# Options
set -sg terminal-overrides ",*:RGB"  # true color support
set -g escape-time 0                 # faster escape response
set -g mouse on
set -g renumber-windows on           # keep window numbers sequential
set -g repeat-time 1000              # allow repeated resize keys

# Options: start indexes from 1
set -g base-index 1
set -g pane-base-index 1


# Theme: borders
set -g pane-border-lines simple
set -g pane-border-style fg=black,bright
set -g pane-active-border-style fg=colour136


# Theme: status
# set -g status-style bg=colour235,fg=black,bright
set -g status-style bg=colour31,fg=colour236,bold
set -g status-left ""
set -g status-right "#[fg=colour236]%H:%M · #[fg=colour236]#S"


# Theme: status windows
# Normal windows: show index and name
set -g window-status-format " #I:#W "

# Current window: show index and name more clearly
set -g window-status-current-format " #I:#W "

# Current window color:
# yellow if zoomed, magenta otherwise
set -g window-status-current-style "#{?window_zoomed_flag,fg=yellow,bold,fg=colour236,bold}"

# Window with bell/activity warning
set -g window-status-bell-style "fg=red,bold"


# Keybindings: pane resize with prefix + Shift-WASD
bind -r W resize-pane -U
bind -r A resize-pane -L
bind -r S resize-pane -D
bind -r D resize-pane -R
